name: Deploy to WordPress.org

on:
  release:
    types: [ published ]

jobs:
  tag:
    # Name
    name: Plugin Deployment
    
    # Virtual Environment to use
    # @see: https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04

    # Steps to deploy
    steps:
      # Checkout (copy) this repository's Plugin to this VM.
      - name: Checkout Plugin
        uses: actions/checkout@v4

      # Installs required packages that must be included in the Plugin
      # as specified in composer.json's "require" section.
      # "require-dev" is ignored by design, as these are only needed for
      # testing
      - name: Run Composer
        run: composer install --no-dev

      # Confirm that expected files exist, to prevent deployment to wordpress.org
      # if e.g. composer install fails.
      - name: Check ConvertKit Library Exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "vendor/convertkit/convertkit-wordpress-libraries/src/class-convertkit-api-traits.php, vendor/convertkit/convertkit-wordpress-libraries/src/class-convertkit-api-v4.php, vendor/convertkit/convertkit-wordpress-libraries/src/class-convertkit-log.php, vendor/convertkit/convertkit-wordpress-libraries/src/class-convertkit-resource.php, vendor/convertkit/convertkit-wordpress-libraries/src/class-convertkit-review-request.php"

      # Deploy to wordpress.org, if expected files exist.
      - name: WordPress Plugin Deploy
        if: steps.check_files.outputs.files_exists == 'true'
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: convertkit
          
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.deploy.outputs.zip-path }}
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip